In [295]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [296]:
df=pd.read_excel('/Halloween_candy.xlsx')
df.head()

ID Q1: going out? Q2: gender Q3: age Q4: country Q5: state/province  \
0  90258773            NaN        NaN     NaN         NaN                NaN   
1  90272821             No       Male      44         USA                 NM   
2  90272829            NaN       Male      49         USA           Virginia   
3  90272840             No       Male      40          us                 or   
4  90272841             No       Male      23         usa           exton pa   

  Q6 | 100 Grand Bar  \
0                NaN   
1                MEH   
2                NaN   
3                MEH   
4                JOY   

  Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes)  \
0                                                NaN                                       
1                                            DESPAIR                                       
2                                                NaN                                       
3                                            DESPAIR                                       
4                                            DESPAIR                                       

  Q6 | Any full-sized candy bar Q6 | Black Jacks  ... Q6 | Vicodin  \
0                           NaN              NaN  ...          NaN   
1                           JOY              MEH  ...      DESPAIR   
2                           NaN              NaN  ...          NaN   
3                           JOY              MEH  ...          JOY   
4                           JOY          DESPAIR  ...          JOY   

  Q6 | Whatchamacallit Bars Q6 | White Bread Q6 | Whole Wheat anything  \
0                       NaN              NaN                       NaN   
1                   DESPAIR          DESPAIR                   DESPAIR   
2                       NaN              NaN                       NaN   
3                       JOY          DESPAIR                   DESPAIR   
4                       JOY          DESPAIR                   DESPAIR   

  Q6 | York Peppermint Patties  \
0                          NaN   
1                      DESPAIR   
2                          NaN   
3                      DESPAIR   
4                          JOY   

                                       Q7: joy other Q8: despair other  \
0                                                NaN               NaN   
1                                             Mounds               NaN   
2                                                NaN               NaN   
3  Reese's crispy crunchy bars, 5th avenue bars, ...               NaN   
4                                                NaN               NaN   

                                  Q9: other comments      Q10: dress Q11: day  
0                                                NaN             NaN      NaN  
1  Bottom line is Twix is really the only candy w...  White and gold   Sunday  
2                                                NaN             NaN      NaN  
3                             Raisins can go to hell  White and gold   Sunday  
4                                                NaN  White and gold   Friday  

[5 rows x 114 columns]

In [297]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2460 entries, 0 to 2459
Columns: 114 entries, ID to Q11: day
dtypes: int64(1), object(113)
memory usage: 2.1+ MB


In [298]:
df.shape

(2460, 114)

In [299]:
df['Q1: going out?'].unique()

array([nan, 'No', 'Yes'], dtype=object)

In [300]:
df['Q1: going out?'].dtype

dtype('O')

In [301]:
df['Q1: going out?'].isnull().sum()

np.int64(110)

In [302]:
df['Q1: going out?'].value_counts()

Q1: going out?
No     2038
Yes     312
Name: count, dtype: int64

In [303]:
df['Q1: going out?'].replace(np.nan,'Unknown',inplace=True)

/tmp/ipython-input-303-2642988228.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Q1: going out?'].replace(np.nan,'Unknown',inplace=True)


In [304]:
df['Q1: going out?'].value_counts()

Q1: going out?
No         2038
Yes         312
Unknown     110
Name: count, dtype: int64

In [305]:
df['Q2: gender'].value_counts()

Q2: gender
Male                  1467
Female                 839
I'd rather not say      83
Other                   30
Name: count, dtype: int64

In [306]:
df['Q2: gender'].isnull().sum()

np.int64(41)

In [307]:
df['Q2: gender'].replace(np.nan,"I'd rather not say",inplace=True)

/tmp/ipython-input-307-2565006767.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Q2: gender'].replace(np.nan,"I'd rather not say",inplace=True)


In [308]:
df['Q2: gender'].value_counts()

Q2: gender
Male                  1467
Female                 839
I'd rather not say     124
Other                   30
Name: count, dtype: int64

In [309]:
df['Q2: gender'].replace('Other',"I'd rather not say",inplace=True)

/tmp/ipython-input-309-2551116041.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Q2: gender'].replace('Other',"I'd rather not say",inplace=True)


In [310]:
df['Q2: gender'].value_counts()

Q2: gender
Male                  1467
Female                 839
I'd rather not say     154
Name: count, dtype: int64

In [311]:
df['Q3: age'].isnull().sum()

np.int64(84)

In [312]:
df['Q3: age'].dtype

dtype('O')

In [313]:
df['Q3: age'].value_counts()

Q3: age
40                                                  92
34                                                  90
37                                                  89
43                                                  86
36                                                  79
                                                    ..
59 on the day after Halloween                        1
old enough                                           1
your mom                                             1
I can remember when Java was a cool new language     1
60+                                                  1
Name: count, Length: 106, dtype: int64

In [314]:
df['Q3: age'].unique()

array([nan, 44, 49, 40, 23, 53, 33, 43, 56, 64, 37, 59, 48, 54, 36, 45,
       25, 34, 35, 38, 58, 50, 47, 16, 52, 63, 65, 41, 27, 31, 61, 46, 42,
       62, 29, 39, 32, 28, 69, 67, 30, 22, 26, 51, 70, 24, 18, 19,
       'Old enough', 57, 60, 66, 12, 'Many', 55, 72, '?', 21, 11, 'no', 9,
       68, 20, 6, 10, 71, 90, 13, '45-55', 312, 99, 7, 'hahahahaha', 88,
       '39.4', 74, 102, 'older than dirt', 17, 15, 8, 75, '5u', 'Enough',
       'See question 2', '24-50', 14, 'Over 50', 100, 76, 1000,
       'sixty-nine', '46 Halloweens.', 'ancient', 77, 'OLD', 'old', 73,
       '70 1/2', 1, 'MY NAME JEFF', 4, '59 on the day after Halloween',
       'old enough', 'your mom',
       'I can remember when Java was a cool new language', '60+'],
      dtype=object)

In [315]:
def clean_age(age):
    if pd.isna(age):
        return np.nan
    age = str(age).strip().lower()
    words = age.split()
    for word in words:
        if word.isdigit():
            return int(word)
        else:
            return np.nan
    if age == "60+":
        return 60
    elif age in ["old enough", "Enough"]:
        return np.nan
    elif '-' in age:
        numbers = [int(x) for x in age.split('-') if x.isdigit()]
        if len(numbers) == 2:
            return (numbers[0] + numbers[1]) // 2
    else:
        return np.nan

In [316]:
df['Q3: age'] = df['Q3: age'].apply(clean_age)

In [317]:
df['Q3: age'] = pd.to_numeric(df['Q3: age'], errors='coerce')

In [318]:
df['Q3: age'].unique()

array([  nan,   44.,   49.,   40.,   23.,   53.,   33.,   43.,   56.,
         64.,   37.,   59.,   48.,   54.,   36.,   45.,   25.,   34.,
         35.,   38.,   58.,   50.,   47.,   16.,   52.,   63.,   65.,
         41.,   27.,   31.,   61.,   46.,   42.,   62.,   29.,   39.,
         32.,   28.,   69.,   67.,   30.,   22.,   26.,   51.,   70.,
         24.,   18.,   19.,   57.,   60.,   66.,   12.,   55.,   72.,
         21.,   11.,    9.,   68.,   20.,    6.,   10.,   71.,   90.,
         13.,  312.,   99.,    7.,   88.,   74.,  102.,   17.,   15.,
          8.,   75.,   14.,  100.,   76., 1000.,   77.,   73.,    1.,
          4.])

In [319]:
df['Q3: age'].isnull().sum()

np.int64(107)

In [320]:
df['Q3: age']=df['Q3: age'].apply(lambda x: np.nan if x>90 else x).astype('Int64')
df['Q3: age'].unique()

<IntegerArray>
[<NA>,   44,   49,   40,   23,   53,   33,   43,   56,   64,   37,   59,   48,
   54,   36,   45,   25,   34,   35,   38,   58,   50,   47,   16,   52,   63,
   65,   41,   27,   31,   61,   46,   42,   62,   29,   39,   32,   28,   69,
   67,   30,   22,   26,   51,   70,   24,   18,   19,   57,   60,   66,   12,
   55,   72,   21,   11,    9,   68,   20,    6,   10,   71,   90,   13,    7,
   88,   74,   17,   15,    8,   75,   14,   76,   77,   73,    1,    4]
Length: 77, dtype: Int64

In [335]:
df['Q3: age'].isnull().sum()

np.int64(113)

In [321]:
df['Q4: country'].unique()

array([nan, 'USA', 'us', 'usa', 'canada', 'Canada', 'Us', 'US', 'Murica',
       'United States', 'uk', 'United Kingdom', 'united states', 'Usa',
       'United staes', 'United States of America', 'UAE', 'England', 'UK',
       'Mexico', 'United states', 'u.s.a.', 'USAUSAUSA', 'america', 35,
       'france', 'U.S.A.', 'finland', 'unhinged states',
       'united states of america', 'US of A', 'Unites States',
       'The United States', 'North Carolina', 'Unied States',
       'Netherlands', 'germany', 'Europe', 'Earth', 'U S', 'u.s.', 'U.K.',
       'Costa Rica', 'The United States of America', 'unite states',
       'U.S.', 46, 'cascadia', 'Australia', 'insanity lately', 'Greece',
       'USA? Hard to tell anymore..', 'merica', 'usas', 'Pittsburgh', 45,
       'United State', 32, 'France', 'australia', 'A', 'Can', 'Canae',
       'New York', 'Trumpistan', 'Ireland', 'United Sates', 'Korea',
       'California', 'Japan', 'USa', 'South africa',
       'I pretend to be from Canada, but 

In [322]:
country_mapping = {
    'usa': 'United States', 'us': 'United States', 'united states': 'United States',
    'murica': 'United States', 'u.s.': 'United States', 'united states of america': 'United States',
    'unites states': 'United States', 'united staes': 'United States', 'u s': 'United States',
    'america': 'United States', 'us of a': 'United States', 'u.s.a': 'United States',
    'canada': 'Canada', 'canada ': 'Canada',
    'france': 'France', 'franc': 'France',
    'germany': 'Germany', 'germ': 'Germany',
    'uk': 'United Kingdom', 'united kingdom': 'United Kingdom', 'england': 'United Kingdom',
    'britain': 'United Kingdom', 'u.k.': 'United Kingdom',
    'australia': 'Australia', 'austral': 'Australia',
    'mexico': 'Mexico',
    'italy': 'Italy',
    'japan': 'Japan',
    'korea': 'South Korea', 'south korea': 'South Korea',
    'switzerland': 'Switzerland', 'swiss': 'Switzerland',
    'denmark': 'Denmark',
    'sweden': 'Sweden',
    'finland': 'Finland',
    'netherlands': 'Netherlands', 'holland': 'Netherlands',
    'belgium': 'Belgium',
    'austria': 'Austria',
    'norway': 'Norway',
    'spain': 'Spain',
    'singapore': 'Singapore',
    'hong kong': 'Hong Kong',
    'new york': 'United States', 'california': 'United States', 'new jersey': 'United States',
    'pittsburgh': 'United States', 'trumpistan': 'United States', 'cascadia': 'United States',
}

In [323]:
df['Q4: country'] = df['Q4: country'].apply(
    lambda x: country_mapping.get(str(x).strip().lower() if pd.notna(x) else np.nan, np.nan)
)

In [324]:
df['Q4: country'].unique()

array([nan, 'United States', 'Canada', 'United Kingdom', 'Mexico',
       'France', 'Finland', 'Netherlands', 'Germany', 'Australia',
       'South Korea', 'Japan', 'Denmark', 'Switzerland', 'Singapore',
       'Hong Kong', 'Spain', 'Sweden'], dtype=object)

In [325]:
df['Q4: country'].isnull().sum()

np.int64(141)

In [326]:
df['Q4: country'].replace(np.nan,'Unknown',inplace=True)

/tmp/ipython-input-326-3294763023.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Q4: country'].replace(np.nan,'Unknown',inplace=True)


In [327]:
df['Q4: country'].unique()

array(['Unknown', 'United States', 'Canada', 'United Kingdom', 'Mexico',
       'France', 'Finland', 'Netherlands', 'Germany', 'Australia',
       'South Korea', 'Japan', 'Denmark', 'Switzerland', 'Singapore',
       'Hong Kong', 'Spain', 'Sweden'], dtype=object)

In [328]:
df['Q5: state/province'].unique()

array([nan, 'NM', 'Virginia', 'or', 'exton pa', 'Colorado', 'ontario',
       'Ontario', 'Wa', 'Quebec', 'NY', 'California', 'Texas', 'NEW YORK',
       'CO', 'IN', 'MN', 'aberdeenshire', 'Alberta', 'Wisconsin, 53705',
       'RI', 'NC', 'Scotland', 'minnesota', 'Michigan', 'Florida',
       'New Jersey', 'VA', 'Los Angeles, California', 'CA', 'New York',
       'Chicago, Illinois', 'Nj', 'Wisconsin', 'Minnesota', 'London',
       'mn', 'TEXAS', 'Illinois', 'District of Columbia', 'Washington',
       'Massachusetts', 'OR', 'Montana', 'massachusetts', 'Abu Dhabi',
       'TX', 'Arizona', 'Dc', 'yukon', 'Pennsylvania', 'MD', 'Ohio',
       'OXFORDSHIRE', 'DC', 'Iowa', 'Mn', 'TN', 'BC', 'Maryland', 'MI',
       'alaska', 'Ny', 'Colorado, Jefferson county ', 'Louisiana', 'pa',
       'CO, Larimer County', 'Nebraska', 'Oregon', 'UT', 'ny', 'CDMX',
       'north carolina', 'Tennessee', 'Knox county, Tennessee',
       'New Mexico', 'Maine', 'maine', 'Virginia, Arlington', 'WA', 'MO',
      

In [329]:
state_province_mapping = {
    # California
    'california': 'California', 'ca': 'California', 'cali': 'California',
    'los angeles': 'California', 'oakland': 'California', 'gloucester': 'California',
    'san diego': 'California', 'ventura': 'California', 'queens': 'California',
    # New York
    'new york': 'New York', 'ny': 'New York', 'brooklyn': 'New York',
    'dutchess county': 'New York', 'ulster county': 'New York',
    # Texas
    'texas': 'Texas', 'tx': 'Texas',
    # Pennsylvania
    'pennsylvania': 'Pennsylvania', 'pa': 'Pennsylvania', 'pittsburgh': 'Pennsylvania',
    'philadelphia': 'Pennsylvania', 'northampton county': 'Pennsylvania', 'raphahannock county': 'Pennsylvania',
    # Virginia
    'virginia': 'Virginia', 'va': 'Virginia', 'henrico': 'Virginia', 'arlington': 'Virginia',
    # Florida
    'florida': 'Florida', 'fl': 'Florida', 'orlando': 'Florida', 'st. augustine': 'Florida',
    # Ohio
    'ohio': 'Ohio', 'cuyahoga county': 'Ohio',
    # Michigan
    'michigan': 'Michigan', 'mi': 'Michigan', 'albuquerque': 'Michigan',
    # Washington
    'washington': 'Washington', 'wa': 'Washington', 'king county': 'Washington',
    'issaquah': 'Washington', 'washington state': 'Washington', 'island county': 'Washington',
    # Arizona
    'arizona': 'Arizona', 'az': 'Arizona', 'maricopa': 'Arizona', 'phoenix': 'Arizona',
    # Maryland
    'maryland': 'Maryland', 'md': 'Maryland',
    # Massachusetts
    'massachusetts': 'Massachusetts', 'ma': 'Massachusetts', 'suffolk': 'Massachusetts',
    # Illinois
    'illinois': 'Illinois', 'il': 'Illinois',
    # Georgia
    'georgia': 'Georgia', 'ga': 'Georgia',
    # Colorado
    'colorado': 'Colorado', 'co': 'Colorado', 'boulder': 'Colorado',
    # New Jersey
    'new jersey': 'New Jersey', 'nj': 'New Jersey', 'merlin': 'New Jersey',
    # Oregon
    'oregon': 'Oregon', 'or': 'Oregon', 'multnomah county': 'Oregon',
    # Connecticut
    'connecticut': 'Connecticut', 'ct': 'Connecticut',
    # North Carolina
    'north carolina': 'North Carolina', 'nc': 'North Carolina',
    # South Carolina
    'south carolina': 'South Carolina', 'sc': 'South Carolina',
    # Tennessee
    'tennessee': 'Tennessee', 'tn': 'Tennessee', 'knox county': 'Tennessee',
    # Alabama
    'alabama': 'Alabama', 'al': 'Alabama',
    # Alaska
    'alaska': 'Alaska', 'ak': 'Alaska',
    # Hawaii
    'hawaii': 'Hawaii', 'hi': 'Hawaii',
    # Idaho
    'idaho': 'Idaho', 'id': 'Idaho',
    # Indiana
    'indiana': 'Indiana', 'in': 'Indiana',
    # Iowa
    'iowa': 'Iowa', 'ia': 'Iowa',
    # Kansas
    'kansas': 'Kansas', 'ks': 'Kansas',
    # Kentucky
    'kentucky': 'Kentucky', 'ky': 'Kentucky',
    # Louisiana
    'louisiana': 'Louisiana', 'la': 'Louisiana',
    # Maine
    'maine': 'Maine', 'me': 'Maine',
    # Minnesota
    'minnesota': 'Minnesota', 'mn': 'Minnesota',
    # Mississippi
    'mississippi': 'Mississippi', 'ms': 'Mississippi',
    # Missouri
    'missouri': 'Missouri', 'mo': 'Missouri', 'st. louis county': 'Missouri',
    # Montana
    'montana': 'Montana', 'mt': 'Montana',
    # Nebraska
    'nebraska': 'Nebraska', 'ne': 'Nebraska',
    # Nevada
    'nevada': 'Nevada', 'nv': 'Nevada',
    # New Hampshire
    'new hampshire': 'New Hampshire', 'nh': 'New Hampshire',
    # New Mexico
    'new mexico': 'New Mexico', 'nm': 'New Mexico', 'dona ana county': 'New Mexico',
    # North Dakota
    'north dakota': 'North Dakota', 'nd': 'North Dakota',
    # Oklahoma
    'oklahoma': 'Oklahoma', 'ok': 'Oklahoma',
    # Rhode Island
    'rhode island': 'Rhode Island', 'ri': 'Rhode Island',
    # South Dakota
    'south dakota': 'South Dakota', 'sd': 'South Dakota',
    # Utah
    'utah': 'Utah', 'ut': 'Utah',
    # Vermont
    'vermont': 'Vermont', 'vt': 'Vermont',
    # West Virginia
    'west virginia': 'West Virginia', 'wv': 'West Virginia',
    # Wisconsin
    'wisconsin': 'Wisconsin', 'wi': 'Wisconsin',
    # Canada Provinces
    'ontario': 'Ontario', 'ontario canada': 'Ontario', 'oshawa': 'Ontario',
    'victoria': 'British Columbia', 'british columbia': 'British Columbia',
    'nova scotia': 'Nova Scotia', 'kingston': 'Ontario',
    # Other
    'sydney': 'New South Wales', 'manchester': 'Greater Manchester',
    'zurich': 'Zurich', 'greater london': 'Greater London',
    #Weird
    'oblivion': np.nan, 'cascadia': np.nan, 'kwazulu-natal': np.nan,
}

In [330]:
df['Q5: state/province'] = df['Q5: state/province'].apply(
    lambda x: state_province_mapping.get(str(x).strip().lower() if pd.notna(x) else np.nan, np.nan)
)

In [331]:
df['Q5: state/province'].unique()

array([nan, 'New Mexico', 'Virginia', 'Oregon', 'Colorado', 'Ontario',
       'Washington', 'New York', 'California', 'Texas', 'Indiana',
       'Minnesota', 'Rhode Island', 'North Carolina', 'Michigan',
       'Florida', 'New Jersey', 'Wisconsin', 'Illinois', 'Massachusetts',
       'Montana', 'Arizona', 'Pennsylvania', 'Maryland', 'Ohio', 'Iowa',
       'Tennessee', 'Alaska', 'Louisiana', 'Nebraska', 'Utah', 'Maine',
       'Missouri', 'New Hampshire', 'Georgia', 'Oklahoma',
       'South Carolina', 'Nevada', 'Alabama', 'North Dakota', 'Kansas',
       'British Columbia', 'West Virginia', 'Kentucky', 'Hawaii',
       'Vermont', 'Greater London', 'Connecticut', 'Mississippi',
       'Greater Manchester', 'New South Wales', 'Nova Scotia',
       'South Dakota', 'Idaho'], dtype=object)

In [332]:
df['Q5: state/province'].replace(np.nan,'Unknown',inplace=True)

/tmp/ipython-input-332-183843842.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Q5: state/province'].replace(np.nan,'Unknown',inplace=True)


In [333]:
df['Q5: state/province'].unique()

array(['Unknown', 'New Mexico', 'Virginia', 'Oregon', 'Colorado',
       'Ontario', 'Washington', 'New York', 'California', 'Texas',
       'Indiana', 'Minnesota', 'Rhode Island', 'North Carolina',
       'Michigan', 'Florida', 'New Jersey', 'Wisconsin', 'Illinois',
       'Massachusetts', 'Montana', 'Arizona', 'Pennsylvania', 'Maryland',
       'Ohio', 'Iowa', 'Tennessee', 'Alaska', 'Louisiana', 'Nebraska',
       'Utah', 'Maine', 'Missouri', 'New Hampshire', 'Georgia',
       'Oklahoma', 'South Carolina', 'Nevada', 'Alabama', 'North Dakota',
       'Kansas', 'British Columbia', 'West Virginia', 'Kentucky',
       'Hawaii', 'Vermont', 'Greater London', 'Connecticut',
       'Mississippi', 'Greater Manchester', 'New South Wales',
       'Nova Scotia', 'South Dakota', 'Idaho'], dtype=object)

KeyError: ''